CREATE TABLE transaction.transaction(
ID INT(11) NOT NULL PRIMARY KEY,
NameOnCard VARCHAR(256),
CardNumber VARCHAR(45),
UnitPrice DECIMAL(10,0),
Quantity INT(11),
TotalPrice DECIMAL(10,0),
ExpDate VARCHAR(16),
CreatedOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CreatedBy VARCHAR(45), 
CardType VARCHAR(45)
);